version: '3.4'

services:
  marketplace.presentation:
    image: ${DOCKER_REGISTRY-}marketplacepresentation
    build:
      context: .
      dockerfile: MarketPlace.Presentation/Dockerfile
    depends_on:
            - SqlServerDb1
    ports:
            - 8001:80 
  SqlServerDb1:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
            - 8002:1433
    environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Aa12345678